### ISSUE TITLE
Contra button has CSS-PRO-TAG

### ISSUE THREAD

**Issue by derunterstrich** [pixelbart/helpful#1]
In the file: /helpful/templates/helpful.php (line: 24) also the contra button gets the CSS-TAG: "helpful-pro" here  would it useful to use "helpful-contra".

https://github.com/pixelbart/helpful/blob/77ee55a5b4869ff84ec0f82e606eef1850521f00/templates/helpful.php#L24

**Comment by pixelbart** [comment]
Thank you! Sorry that I see this only now. I didn't expect anyone to report anything on Github here.
