### ISSUE TITLE
Live Ausgabe print_r

### ISSUE THREAD

**Issue by derunterstrich** [pixelbart/helpful#14]
Guten Morgen,

ich musste heute morgen feststellen, dass ich auf allen Seiten den die print_r Ausgabe habe:

https://github.com/pixelbart/helpful/blob/382401841c195f8ba6ae0fd5b2b1595ec1ee5d3b/core/modules/class-frontend.php#L388

Ich habe seit Wochen nichts an dem Tool geändert. Ist das ein Bug, oder hatte sich was bei den Einstellungen geändert? Wenn 2., Was muss ich tun damit die Ausgabe nicht mehr erscheint? 

WP: latest
Helpfull: latest

**Comment by pixelbart** [comment]
Danke dir, wurde mir bereits gemeldet und habe ich gefixt. Das war meine Debug-Ausgabe, die ich leider vergessen hatte, wieder rauszunehmen.
