### ISSUE TITLE
Default filling no longer works when the plugin is reinstalled.

### ISSUE THREAD

**Issue by pixelbart** [pixelbart/helpful#15]
There is still the "problem" that the default values are not set when Helpful is installed for the first time.

I already know what this is and also why I disabled this. I still need to check here if Helpful is freshly installed or just updated. For that, I still need to see what option is set during the first installation, so I can use that option to check.

This should all happen as "secretly" as possible, so that users who are already using Helpful don't notice anything about the fix.

* https://github.com/pixelbart/helpful/blob/master/core/modules/class-core.php#L55
* https://github.com/pixelbart/helpful/blob/master/core/modules/class-core.php#L87
* https://github.com/pixelbart/helpful/blob/master/core/modules/class-core.php#L150

**Comment by seb86** [comment]
@pixelbart Now I know why I had to manually set things up myself. I hope you get this issue solved quick as it would defiantly improve the out of the box experience.
