### ISSUE TITLE
Header issue with  version 4.2.11

### ISSUE THREAD

**Issue by melbarra88** [pixelbart/helpful#2]
Hi,
Just after upgrading to the new version 4.2.11, an error message keeps showing on my pages :

> Warning: session_start(): Cannot start session when headers already sent in /homepages/23/d818374128/htdocs/app818374172/wp-content/plugins/helpful/core/classes/class-helpful-helper-values.php on line 158
>
> Warning: Cannot modify header information - headers already sent by (output started at /homepages/23/d818374128/htdocs/app818374172/wp-content/themes/rang-mahal/header.php:13) in /homepages/23/d818374128/htdocs/app818374172/wp-content/plugins/helpful/core/classes/class-helpful-helper-values.php on line 162

Is there any workaround to this issue ?
Thanks.

**Comment by pixelbart** [comment]
Thanks! Should be fixed with the last version.
