### ISSUE TITLE
Error version 4.2.12

### ISSUE THREAD

**Issue by cerulean-terao** [pixelbart/helpful#3]
Hi,
Just after upgrading to the new version 4.2.12, an error message keeps showing on dashboard
`Warning: usort() expects parameter 1 to be array, null given in /app/public/wp-content/plugins/helpful/core/classes/class-helpful-helper-stats.php on line 1054`
`Warning: usort() expects parameter 1 to be array, null given in /app/public/wp-content/plugins/helpful/core/classes/class-helpful-helper-stats.php on line 1139`

and an error message keeps showing on page
`Warning: session_start(): Cannot start session when headers already sent in /app/public/wp-content/plugins/helpful/core/classes/class-helpful-helper-values.php on line 158`

**Comment by pixelbart** [comment]
Thanks! Should be fixed with the last version.
