### ISSUE TITLE
File_get_contents gives error

### ISSUE THREAD

**Issue by hejamartin** [pixelbart/helpful#36]
Hi Helpful.

The 4.5.0 seemed to break the previous look we had on the frontend Yes/No buttons.
I installed the 4.5.5 to hopefully address this issue since it was released a couple of hours ago.

But the other issue that seems to be more of a deal breaker is the errors output by php on my local development machine.

<img width="1006" alt="image" src="https://user-images.githubusercontent.com/533316/159348639-a2b59fe1-3963-4ea9-b087-b0b8074511f3.png">

For example, the feedback-email.txt do exist on that given location - but still seems to be an issue with the new approach in the code. Is there something that should be addressed on your end?

**Comment by pixelbart** [comment]
Hi @hejamartin 

this should be a problem with the localhost. You need to give the localhost a http:// to make it work better. Also allow_url_open must be set to true in the PHP-ini file.

I will put the old option back in, in case file_get_contents throws an error.

Thank you for your feedback!

Greetings Kevin

**Comment by hejamartin** [comment]
Great, wp_remote_get the way to go. Good change.
