### ISSUE TITLE
"Undefined index: exists-hide" when hiding after voting is not enabled

### ISSUE THREAD

**Issue by zarino** [pixelbart/helpful#4]
I’m seeing this exception in the public front end, once I reload any page that I’ve already voted on:

> Notice: Undefined index: exists-hide in /home/vagrant/wordpress/wp-content/plugins/helpful/core/classes/class-helpful-shortcodes.php on line 91

This happens regardless of whether the voting form is being inserted automatically by the `Helpful > Settings > Post types` settings, or via the `[helpful]` shortcode. (Only difference is, in the case of the shortcode, the exception happens on line 153 of `class-helpful-shortcodes.php`, obviously.)

The "Hide Helpful when voted" checkbox in `Helpful > Settings > General` is _not_ checked.

It looks like `class-helpful-shortcodes.php` expects `$helpful['exists-hide']` to exist if `$helpful['exists'] === 1`, on [line 91 of class-helpful-shortcodes.php](https://github.com/pixelbart/helpful/blob/47c86de69ae7410e5a54cc24919be180cb92957e/core/classes/class-helpful-shortcodes.php#L91), and [again on line 153](https://github.com/pixelbart/helpful/blob/47c86de69ae7410e5a54cc24919be180cb92957e/core/classes/class-helpful-shortcodes.php#L153).

But in my case, this is what’s inside of the `$helpful` array:

```
Array
(
    [heading_tag] => h3
    [heading] => Is this page useful?
    [content] => 
    [button_pro] => Yes
    [button_contra] => No
    [counter] => 
    [count_pro] => 1
    [count_pro_percent] => 100
    [count_contra] => 0
    [count_contra_percent] => 0
    [credits] => 
    [credits_html] => Helpful
    [exists] => 1
    [exists_text] => Thanks for your feedback.
    [post_id] => 28
)
```

Should `class-helpful-shortcodes.php` check whether the `'exists-hide'` key is set, first, before it checks the equality to 1? eg:

```
if ( 1 === $helpful['exists'] ) {
    if ( isset($helpful['exists-hide']) && 1 === $helpful['exists-hide'] ) {
```

Or does this work for everyone else, and I’m just missing some required set-up that‘d make the `'exists-hide'` key exist?

@pixelbart I’m happy to submit a PR that introduces `isset()` checks in `class-helpful-shortcodes.php` if you’d like?

**Comment by pixelbart** [comment]
You're right. In both cases, I forgot to check if the variable exists. Hopefully this will be fixed in 4.2.13!

**Comment by zarino** [comment]
@pixelbart Would it help for me to submit a PR, or do you already have it in hand?

**Comment by pixelbart** [comment]
I have already done this. I had to fix two more bugs in the process. But I only noticed it now. The update will be published on wp.org immediately.

**Comment by zarino** [comment]
Amazing. You rock 🤘
