### ISSUE TITLE
Feedback form message not saved to database, name/email fields not showing

### ISSUE THREAD

**Issue by vtamm** [pixelbart/helpful#55]
Hi, we are running into a peculiar issue where the text submitted in the fields of the feedback form are not saved. The request to `admin-ajax.php` includes the message, as we can see here:

![CleanShot 2022-04-27 at 08 59 55](https://user-images.githubusercontent.com/2803301/165461252-8c8d069c-8b8c-4978-ae7b-3b2879096fb4.png)

... but I have yet to figure out what happens after that request is sent. Also of note is that while we do not need Name or Email in the form, I activated them in the plugin settings but they are still not included in the form:

![CleanShot 2022-04-27 at 09 07 56](https://user-images.githubusercontent.com/2803301/165461724-71e33499-a738-4404-867e-b2a40e932569.png)
![CleanShot 2022-04-27 at 09 10 36](https://user-images.githubusercontent.com/2803301/165461739-9cf23075-c06a-47ab-b5a1-25398292361e.png)

I understand there are many different variables at play, including our own code which of course could be affecting your plugin. But in order to further troubleshoot this issue, would you mind giving me some pointers as to where in the plugin code I should look closer to figure out why the message field is not saved?

**Comment by pixelbart** [comment]
@vtamm thank you for your message!

Everything looks good so far. I don't see any errors there either. The place where the message is saved, you can find here:

* https://github.com/pixelbart/helpful/blob/master/core/helpers/class-feedback.php#L115

The variable $request is really the `$_GET`, `$_POST` or `$_REQUEST`. There you can check if something gets in the way of your code.

It is important that the fields for email and name are only shown if you are not logged in. If you are logged in, Helpful is so smart and takes the data from your profile.

You can also enable `WP_DEBUG_LOG` and `WP_DEBUG`. Theoretically, the error should then be saved in your `debug.log` inside of the wp-content dir, if the message can't be saved.

* https://github.com/pixelbart/helpful/blob/master/core/functions/helpers.php#L52

wp-config.php :
```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
define( 'WP_DEBUG_LOG', true );
```

Stay healthy!

Greetings Kevin

**Comment by vtamm** [comment]
@pixelbart so after about five hours of digging and troubleshooting, I finally found the issue. I had checked the **Reset Feedback** checkbox on the System tab of the plugin settings expecting that it would uncheck itself after running the reset once, but unfortunately _the checkbox remains checked_ so any feedback submitted is automatically deleted by the [`reset_feedback` method in the `System` class](https://github.com/pixelbart/helpful/blob/master/core/tabs/class-system.php#L238-L252).

I have submitted [a pull request](https://github.com/pixelbart/helpful/pull/56) for you to review which fixes this issue, although there might be more to this for you to look into as well as per my PR's description.

**Comment by pixelbart** [comment]
@vtamm once again, a big sorry for the circumstance! This is already a fatal error that happened here, the more I'm glad that you could find a solution.

Your pull I have approved, thanks for that! Sometimes you're in a tunnel and then you just forget places you shouldn't. Happened to me here again apparently.

Thank you again!

Stay healthy

**Comment by vtamm** [comment]
@pixelbart closing this issue now as the fix has been merged. Thank you!
